### ISSUE TITLE
STL file for case bottom

### ISSUE THREAD

**Issue by nikolaskaralis** [jazzlw/arduino_bnc#1]
Hi Jazz,

awesome project! 
I've been meaning to do something like this for years.

The bottom case file is .ipt (Inventor format).
Could you by any chance provide a .stl file?

Thanks in advance!

**Comment by jazzlw** [comment]
Thanks, I'm glad you like it!  And thanks for catching that, it was definitely supposed to be an stl file!  I've fixed it now, let me know if it works of if you have any other questions!

https://github.com/jazzlw/arduino_bnc/commit/d4fa02aca514f6f7a8b0c5207c1f0d6cd495ebae
